### ISSUE TITLE
Desenvolvimento Dijkstra

### ISSUE THREAD

**Issue by SamuelBFavarin** [SamuelBFavarin/grafos.js#2]
# Dijsktra
Desenvolvimento de algoritmo Dijsktra para a busca de caminhos com peso.
O Algoritmo deve ser implementado para grafos ponderados e não direcionados.
Deve-se aplicar a busca para Algoritmos com e sem destino

- [ ] Dijsktra com destino
- [ ] Dijsktra sem destino

**Material de apoio: **

- https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm
- https://github.com/nojacko/dijkstras-js/blob/master/Dijkstras.js
- https://hackernoon.com/how-to-implement-dijkstras-algorithm-in-javascript-abdfd1702d04

**Comment by zelucena** [comment]
solucionado conforme o slide
