### ISSUE TITLE
Ajuste de integração de Canvas  + Grafo

### ISSUE THREAD

**Issue by vinicius1209** [SamuelBFavarin/grafos.js#3]
É necessário ajustar a integração, pois o Samuel desenvolveu novas interações no arquivo gui.html.
- [x]  Prestar atenção nos índices que o Samuel usou e nos índices que usei em cavas.js
- [x]  Usar a própria classe grafo ao invés de uma nova variável

**Comment by vinicius1209** [comment]
@SamuelBFavarin Vi que você mudou a forma de desenhar. Colocou mais um índice de peso tanto no vértice, quanto nas ligações. Nao entendi pq você colocou peso nos dois array's. Acredito que esse índice novo ta dando problema pra desenhar e pintar..

**Comment by SamuelBFavarin** [comment]
@vinicius1209 Antigamente ele não desenhava o valor do peso, apenas uma string chamada "peso". Utilizei aquela forma ali pois vi que seria o jeito mais fácil de enviar o peso para o desenho. É necessário passar agora também o peso da ligação para o desenho. Caso queiras modificar a forma de envio, podes ficar a vontade, mas acredito que assim é a forma mais simples de desenhar.

**Comment by vinicius1209** [comment]
@SamuelBFavarin blz, a gente vê a noite

**Comment by vinicius1209** [comment]
@SamuelBFavarin  não lembro tudo de ontem. Ficou funcionando o lance dos pesos ontem?

**Comment by SamuelBFavarin** [comment]
Ainda não está funcionando, vou fazer as correções essa tarde

**Comment by SamuelBFavarin** [comment]
Integração está funcionando
