### ISSUE TITLE
Coloração DSATUR

### ISSUE THREAD

**Issue by vinicius1209** [SamuelBFavarin/grafos.js#4]
Dsatur 👍 

- [x] Ordenar os vértices pelo maior grau
- [x] Iniciar todos os vértices com cor = "Sem Cor"
- [x] Iniciar todos os vértices com grau de saturação = 0
- [ ] Aplicar as cores de acordo com o pseudo código

**Comment by vinicius1209** [comment]
**********PSEUDO CÓDIGO*********
Colorir o vértice com maior grau com a primeira cor
  Enquanto existir um vértice sem cor no grafo {
    Selecionar o vértice com maior grau de saturação, em caso de empate, escolher o com maior grau 
      dentre os de maior saturação
     Atribuir para este vértice a primeira cor que não esteja em um vértice adjacente
}

**Comment by vinicius1209** [comment]
Grafo.prototype.atualizaGrauSaturacao = function(listaDsatur){

        //Percorro a lista, encontro B
        for(i = 0; i < listaDsatur.length; i ++){
            //Busco o total de ligações de B por exemplo, sera retornado 3 (A, C, E)
            for(j = 0; j < this.ligacao[listaDsatur[i][0]].length; j ++){   
                
                //Preciso percorrer os vizinhos de A por exemplo e testar as cores para somar (D, B)
                for(k = 0; k < this.ligacao[this.ligacao[listaDsatur[i][0]][j][0]].length; k ++){ 

                    //Agora vou acessar as cores de cada vizinho
                    for(l = 0; l < listaDsatur.length; l++){
                        
                        //Encontro as informações de D por exemplo. Agora vou testar se a cor de D é diferente de A, e diferente de B
                        if(listaDsatur[l][0] == this.ligacao[this.ligacao[listaDsatur[i][0]][j][0]][k][0]){

                            //Procuro as informações de A
                            for(m = 0; m < listaDsatur.length; m++){
                                
                                if(listaDsatur[m][0] == this.ligacao[listaDsatur[i][0]][j][0]){
                                    //Se cor de A é diferente de cor de D, e cor de D é diferente de Sem Cor
                                    if(listaDsatur[m][2] != listaDsatur[l][2] && listaDsatur[l][2] != "Sem Cor"){

                                        if(listaDsatur[l][2] != listaDsatur[i][2]){

                                            listaDsatur[m][3] = listaDsatur[m][3] + 1;

                                        }

                                    }
                                
                                }

                            }
                            
                        }

                    }

                }

            }
            
        }

        return listaDsatur;
    };

**Comment by vinicius1209** [comment]
Acredito que arrumar a ordenação por grau de saturação o código de coloração ja funcione 💯

**Comment by vinicius1209** [comment]
![image](https://user-images.githubusercontent.com/14108988/31247184-303a8456-a9e6-11e7-9674-4c5cc83d2081.png)

Ta quase.... Falta entender pq a cor de E ficou diferente...

Ainda está com problema para alterar o grau de saturação

@SamuelBFavarin , @zelucena

**Comment by SamuelBFavarin** [comment]
Vamos ver isso agora a noite!

**Comment by SamuelBFavarin** [comment]
Boa noite, embora a coloração esteja funcionando perfeitamente, a principal saída para o algoritmo DSATUR é a saturação. Quando colorimos com o algoritmo WELSH ou o DESATUR, quase sempre o resultado da coloração é o mesmo. 
Tentei arrumar o código, só que sem muito sucesso.

**Comment by vinicius1209** [comment]
@SamuelBFavarin @zelucena Continua pintando corretamente (Agora sem ser fixo pelo Welsh), mas ainda o grau de saturação de B, E (Por exemplo), estão errados por terem 3 ligações cada :

- [x] Está ordenando
- [x] Está iniciando tudo com zero
- [x] Está buscando corretamente o maior grua de saturação (Apesar do erro)
- [ ] Ainda não está atualizando o grau corretamente 👎 

![image](https://user-images.githubusercontent.com/14108988/31296223-e26d26d4-aab7-11e7-99b7-5290e7716171.png)

**Comment by vinicius1209** [comment]
![image](https://user-images.githubusercontent.com/14108988/31296275-192890b4-aab8-11e7-846e-b4524a47a29d.png)

**Comment by vinicius1209** [comment]
@SamuelBFavarin @zelucena Consegui!!

**Comment by SamuelBFavarin** [comment]
Boaaa!!!!
