### ISSUE TITLE
Tema para entrega do último trabalho da M3

### ISSUE THREAD

**Issue by SamuelBFavarin** [SamuelBFavarin/grafos.js#6]
Bom dia senhores, deixo essa issue aqui para que pensamos no tema do nosso último trabalho de grafos. 
Lembrando que devemos aplicar grafos para solucionar algum problema real. Podemos utilizar algoritmos que já criamos (Coloração, árvore mínima), ou pesquisar novos algoritmos.

Exemplos que podemos utilizar são:
- Caixeiro Viajante (https://en.wikipedia.org/wiki/Travelling_salesman_problem)
- Coloração de mapas (https://en.wikipedia.org/wiki/Graph_coloring)

Vamos discutindo...

**Comment by SamuelBFavarin** [comment]
Então galera, a apresentação é amanha e nem temos um tema definido.
Estava pensando em usar um problema clássico de grafos que utiliza coloração para resolver.
"O problema da galeria de arte", basicamente tem como objetivo otimizar o número de câmeras que devem ser instaladas para cobrir toda a galeria

![image](https://user-images.githubusercontent.com/17628602/33713407-361c53b8-db32-11e7-961b-a6883f6f06a8.png)

Deixo o link do artigo. Não precisamos implementar o algoritmo, mas devemos apresentar o problema, definir como é feito o algoritmo, pegar resultados de alguém que já implementou e dar uma conclusão do assunto.

**Comment by SamuelBFavarin** [comment]
Segue o link do artigo:
https://atitudereflexiva.wordpress.com/2017/09/01/o-problema-da-galeria-de-arte/

**Comment by zelucena** [comment]
cara eu vou dar uma olhada a noite no artigo mas a proposta parece
interessante, pelo título.Eu topo. Posso pesquisar uns artigos em inglês
também. tem só que apresentar ou tem que fazer uma parte escrita?

2017-12-07 9:42 GMT-02:00 Samuel Brati Favarin <notifications@github.com>:

**Comment by SamuelBFavarin** [comment]
O trabalho é apenas a apresentação. Não há necessidade de fazermos o algoritmo. Vou mandar um e-mail para o professor informando a troca do nosso tema.

Palavra chave para a pesquisa de artigos: Art gallery problem

Referências é oque não falta
https://en.wikipedia.org/wiki/Art_gallery_problem
https://link.springer.com/chapter/10.1007%2FBFb0032069?LI=true
http://www.sciencedirect.com/science/article/pii/S0925772100000237
http://www.ic.unicamp.br/~rezende/ensino/mo619/2008s1/ArtGallery-PJR-Handout.pdf
http://www.csun.edu/~sf70713/fall05/ArtGalleryProblems.pdf

**Comment by SamuelBFavarin** [comment]
Deixo o link da apresentação para que vocês também possam edita-la.
https://docs.google.com/presentation/d/1BGeYSa-GnYgF9LqGYgsrf6FVPptt_TsJUS209qMB61M/edit?usp=sharing

**Comment by SamuelBFavarin** [comment]
Uma fonte que aborda o problema de uma forma bem completa
https://linux.ime.usp.br/~piva/mac499/monografia.pdf

**Comment by zelucena** [comment]
Compartilhei um item com você:

Python.html
https://drive.google.com/file/d/1QB0xUAK4ezyl1xU1Uz10XYNSuWTE1IxM/view?usp=sharing&ts=5beaf8cb

Não é um anexo; está armazenado on-line. Para abrir este item, basta clicar  
no link acima.
