### ISSUE TITLE
Trabalho M3.1 

### ISSUE THREAD

**Issue by SamuelBFavarin** [SamuelBFavarin/grafos.js#7]
Por ser apenas um algoritmo, crio essa issue para discutirmos sobre o mesmo.

**Comment by SamuelBFavarin** [comment]
Fonte -> Tem apenas saídas
Sorvedouro -> Tem apenas entradas

**Comment by SamuelBFavarin** [comment]
`var grafoAuxiliar = Object.assign({}, grafo);`

Essa função não copia um objeto e o torna independente, ele apenas tonar um "ponteiro" para o objeto inicial. Isso acontece problemas quando modificamos um objeto, o outro também é alterado.

**Comment by SamuelBFavarin** [comment]
` var grafoAuxiliar = JSON.parse(JSON.stringify(grafo));`

Essa função resolveu o problema acima

**Comment by vinicius1209** [comment]
O professor disse que provavelmente nosso erro está no DFS. Pelo loop nele. Ele disse que podiamos usar um status de "visitado".

**Comment by SamuelBFavarin** [comment]
Bora tentar terminar?

**Comment by vinicius1209** [comment]
terminado
